import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import Candle from './candle';



export default function Home() {



  
  var listArr =[{
    text:'അതിനാല്‍, വേണ്ട സമയത്തു കരുണയും കൃപാവരവും ലഭിക്കുന്നതിനായി നമുക്കു പ്രത്യാശയോടെ കൃപാവരത്തിന്റെ സിംഹാസനത്തെ സമീപിക്കാം.',
    author: 'ഹെബ്രായർ 4:16'
  },
  
  {
    text:'നിങ്ങള്‍ അപേക്ഷകളോടുംയാചനകളോടും കൂടെ എല്ലാസമയവും ആത്മാവില്‍ പ്രാര്‍ഥനാനിരതരായിരിക്കുവിന്‍. അവിശ്രാന്തം ഉണര്‍ന്നിരുന്ന് എല്ലാ വിശുദ്ധര്‍ക്കുംവേണ്ടി പ്രാര്‍ഥിക്കുവിന്‍',
    author: 'എഫേസൂസ്‌ 6:18'
  },
  {
    text:'സന്ധ്യയിലും പ്രഭാതത്തിലും മധ്യാഹ്‌നത്തിലും ഞാന്‍ ആവലാതിപ്പെട്ടു കരയും; അവിടുന്ന് എന്റെ സ്വരം കേള്‍ക്കും.',
    author: 'സങ്കീർത്തനങ്ങൾ 55:17'
  },
  {
    text:'ഞാന്‍ കര്‍ത്താവിനെ സ്‌നേഹിക്കുന്നു, എന്റെ പ്രാര്‍ഥനയുടെ സ്വരംഅവിടുന്നു ശ്രവിച്ചു. അവിടുന്ന് എനിക്കു ചെവിചായിച്ചുതന്നു, ഞാന്‍ ജീവിതകാലം മുഴുവന്‍ അവിടുത്തെ വിളിച്ചപേക്ഷിക്കും.',
    author: 'സങ്കീർത്തനങ്ങൾ 116:1, 2'
  }
  ];
  const [selected, updateVal]= useState(listArr[0])
  const getRandomValue=()=>{
    const num=  Math.floor(Math.random() * listArr.length) || 0;
    const newVal = listArr[num];
    updateVal(newVal)
 
   }
   

  return (
    <div className={styles.container}>
      <Head>
        <title>Vachanapetti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.glass}>

<p className={styles.textStyle}>{selected.text}  </p>
      <p className={styles.textStyle}><em>- {selected.author}</em></p>


      <div className={styles.bottom}>
				
						<span className ={styles.new_message} onClick ={getRandomValue}>
            പുതിയ സന്ദേശം
						</span>
					</div>

    </div>







<div className={styles.wrapper}>
<Candle></Candle>
<Candle></Candle>
<Candle></Candle>
</div>
 


  
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developer by{' '}
          <span className={styles.logo}>
           Aan Arakal
          </span>
        </a>
      </footer>
    </div>
  )
}
